spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BstDB?useSSL=false&serverTimezone=UTC
    driver-class-name: org.h2.Driver
    username: root
    password: Password123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true